// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList.data;

namespace TodoList.Migrations
{
    [DbContext(typeof(Appdbcontext))]
    [Migration("20210202124839_initial migration ")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("TodoList.Models.Cartegory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cartegories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("TodoList.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("TodoList.Models.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartegoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartegoryId");

                    b.HasIndex("StatusId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartegoryId = 1,
                            Description = "open visual studio",
                            DueDate = new DateTime(2021, 2, 2, 13, 48, 38, 655, DateTimeKind.Local).AddTicks(1447),
                            StatusId = 1,
                            Title = "Code"
                        });
                });

            modelBuilder.Entity("TodoList.Models.Tasks", b =>
                {
                    b.HasOne("TodoList.Models.Cartegory", "Cartegory")
                        .WithMany("Task")
                        .HasForeignKey("CartegoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoList.Models.Status", "Status")
                        .WithMany("Task")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartegory");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TodoList.Models.Cartegory", b =>
                {
                    b.Navigation("Task");
                });

            modelBuilder.Entity("TodoList.Models.Status", b =>
                {
                    b.Navigation("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
